// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl3OVfhaqz7BfE_NfyWTroWpwz9hmLb-U',
    appId: '1:533321577513:web:d47a02aab636c4e81d5838',
    messagingSenderId: '533321577513',
    projectId: 'expenseapp-62d4e',
    authDomain: 'expenseapp-62d4e.firebaseapp.com',
    storageBucket: 'expenseapp-62d4e.firebasestorage.app',
    measurementId: 'G-M5NYDK3VYY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEBCOUTNCqM1eLQsCmqkz8HlPOARAS_e0',
    appId: '1:533321577513:android:5d5775fb2a5e690f1d5838',
    messagingSenderId: '533321577513',
    projectId: 'expenseapp-62d4e',
    storageBucket: 'expenseapp-62d4e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIqiLOD0UuDVZm_FGBdzMxAcH7PYYPZy0',
    appId: '1:533321577513:ios:8f5894efd3d7e76b1d5838',
    messagingSenderId: '533321577513',
    projectId: 'expenseapp-62d4e',
    storageBucket: 'expenseapp-62d4e.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIqiLOD0UuDVZm_FGBdzMxAcH7PYYPZy0',
    appId: '1:533321577513:ios:8f5894efd3d7e76b1d5838',
    messagingSenderId: '533321577513',
    projectId: 'expenseapp-62d4e',
    storageBucket: 'expenseapp-62d4e.firebasestorage.app',
    iosBundleId: 'com.example.expenseApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl3OVfhaqz7BfE_NfyWTroWpwz9hmLb-U',
    appId: '1:533321577513:web:520ad92b59f99e9c1d5838',
    messagingSenderId: '533321577513',
    projectId: 'expenseapp-62d4e',
    authDomain: 'expenseapp-62d4e.firebaseapp.com',
    storageBucket: 'expenseapp-62d4e.firebasestorage.app',
    measurementId: 'G-5YMGJCJRKY',
  );
}
